# Generated by Django 5.1.6 on 2025-04-12 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_rename_profile_picture_profile_profile_pic_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='phone_number',
            new_name='ph_number',
        ),
    ]
