# Generated by Django 5.1.6 on 2025-04-12 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_rename_phone_number_profile_ph_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='emg_contact_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='emg_contact_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='emg_contact_number',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='profile',
            name='emg_contact_relation',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name='MedicalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_group', models.CharField(blank=True, max_length=3)),
                ('allergies', models.TextField(blank=True)),
                ('medical_conditions', models.TextField(blank=True)),
                ('on_going_medications', models.TextField(blank=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medical_info', to='account.profile')),
            ],
        ),
    ]
