# Generated by Django 5.1.6 on 2025-04-13 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_profile_emg_contact_address_profile_emg_contact_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email_notification',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='reminders',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='sms_notification',
            field=models.BooleanField(default=True),
        ),
    ]
