# Generated by Django 5.1.6 on 2025-04-18 15:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_profile_email_notification_profile_reminders_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalinfo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 1, 1, 12, 0)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicalinfo',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
