# Generated by Django 5.2.1 on 2025-07-08 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0027_calls_lab_report_notes_calls_prescription_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('call', 'Call'), ('appoinment', 'Appoinment'), ('text', 'Text'), ('started', 'Started'), ('notes', 'Notes')], default='text', max_length=20),
        ),
    ]
