# Generated by Django 5.1.6 on 2025-04-18 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0005_profile_email_notification_profile_reminders_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick_name', models.CharField(blank=True, max_length=255)),
                ('doc_type', models.CharField(blank=True, max_length=100)),
                ('file', models.FileField(blank=True, upload_to='patients_documents/')),
                ('from_our_clinic', models.BooleanField(default=False)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patients_documents', to='account.profile')),
            ],
        ),
    ]
