# Generated by Django 5.1.6 on 2025-04-18 15:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 1, 1, 12, 0)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='documents',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
