# Generated by Django 5.1.6 on 2025-04-18 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_documents_created_at_documents_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
