# Generated by Django 5.1.6 on 2025-04-18 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_medicalinfo_created_at_medicalinfo_updated_at'),
        ('patient', '0003_documents_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patients_documents', to='account.profile'),
        ),
    ]
